author: Guilherme Bertuol
title: O Duplo
email: guilherme.bertuol@gmail.com
description: >
  O Duplo means the double, the couple, Jorge Luis Borges.
lang: "pt-BR"

# Build settings
markdown: kramdown
timezone: Europe/London
encoding: "utf-8"

# serve settings
port: 8080
host: "localhost"
url: "http://localhost:8080"
